"""Add relation table

Revision ID: eef590dde83a
Revises: 794e756326ce
Create Date: 2022-10-09 11:29:00.252376

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "eef590dde83a"
down_revision = "794e756326ce"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "relation",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_updated", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("short_name", sa.String(length=32), nullable=True),
        sa.Column("kvk_number", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("account", sa.String(), nullable=True),
        sa.Column("budget", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("relation")
    # ### end Alembic commands ###
